#include "../inc/tui_bonus.h"
#include <ncurses.h>
#include <unistd.h>

int	init_colors(void)
{
	if (has_colors() == FALSE)
	{
		printf("Your terminal does not support color\n");
		endwin();
		return (-1);
	}
	start_color();
	setup_color_pairs();
	return (0);
}

void	setup_color_pairs(void)
{
	init_pair(1, COLOR_RED, COLOR_BLACK);
	init_pair(2, COLOR_GREEN, COLOR_BLACK);
	init_pair(3, COLOR_YELLOW, COLOR_BLACK);
	init_pair(4, COLOR_BLUE, COLOR_BLACK);
	init_pair(5, COLOR_MAGENTA, COLOR_BLACK);
	init_pair(6, COLOR_CYAN, COLOR_BLACK);
	init_pair(7, COLOR_WHITE, COLOR_BLACK);
	init_color(CUSTOM_COLORS_START + 0, RGB_TO_NCURSES_COLOR(0xfa),  RGB_TO_NCURSES_COLOR(0xf8),  RGB_TO_NCURSES_COLOR(0xef));
	init_pair(CUSTOM_COLORS_START + 0, CUSTOM_COLORS_START + 0, CUSTOM_COLORS_START + 0);
	init_color(CUSTOM_COLORS_START + 1, RGB_TO_NCURSES_COLOR(0xee), RGB_TO_NCURSES_COLOR(0xe4), RGB_TO_NCURSES_COLOR(0xda)); /* color-2 */
	init_pair(CUSTOM_COLORS_START + 1, CUSTOM_COLORS_START + 1, CUSTOM_COLORS_START + 12);
	init_color(CUSTOM_COLORS_START + 2, RGB_TO_NCURSES_COLOR(0xee),  RGB_TO_NCURSES_COLOR(0xe1),  RGB_TO_NCURSES_COLOR(0xc9));  /* color-4 */
	init_pair(CUSTOM_COLORS_START + 2, CUSTOM_COLORS_START + 2, CUSTOM_COLORS_START + 12);
	init_color(CUSTOM_COLORS_START + 3, RGB_TO_NCURSES_COLOR(0xf3),  RGB_TO_NCURSES_COLOR(0xb2),  RGB_TO_NCURSES_COLOR(0x7a));  /* color-8  */
	init_pair(CUSTOM_COLORS_START + 3, CUSTOM_COLORS_START + 3, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 4, RGB_TO_NCURSES_COLOR(0xf6),  RGB_TO_NCURSES_COLOR(0x96),  RGB_TO_NCURSES_COLOR(0x64));  /* color-16 */
	init_pair(CUSTOM_COLORS_START + 4, CUSTOM_COLORS_START + 4, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 5, RGB_TO_NCURSES_COLOR(0xf7),  RGB_TO_NCURSES_COLOR(0x7c),  RGB_TO_NCURSES_COLOR(0x5f));  /* color-32 */
	init_pair(CUSTOM_COLORS_START + 5, CUSTOM_COLORS_START + 5, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 6, RGB_TO_NCURSES_COLOR(0xf7),  RGB_TO_NCURSES_COLOR(0x5f),  RGB_TO_NCURSES_COLOR(0x3b));  /* color-64 */
	init_pair(CUSTOM_COLORS_START + 6, CUSTOM_COLORS_START + 6, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 7, RGB_TO_NCURSES_COLOR(0xed),  RGB_TO_NCURSES_COLOR(0xd0),  RGB_TO_NCURSES_COLOR(0x73));  /* color-128 */
	init_pair(CUSTOM_COLORS_START + 7, CUSTOM_COLORS_START + 7, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 8, RGB_TO_NCURSES_COLOR(0xed),  RGB_TO_NCURSES_COLOR(0xcc),  RGB_TO_NCURSES_COLOR(0x62));  /* color-256 */
	init_pair(CUSTOM_COLORS_START + 8, CUSTOM_COLORS_START + 8, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 9, RGB_TO_NCURSES_COLOR(0xed),  RGB_TO_NCURSES_COLOR(0xc9),  RGB_TO_NCURSES_COLOR(0x50));  /* color-512 */
	init_pair(CUSTOM_COLORS_START + 9, CUSTOM_COLORS_START + 9, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 10, RGB_TO_NCURSES_COLOR(0xed),  RGB_TO_NCURSES_COLOR(0xc5),  RGB_TO_NCURSES_COLOR(0x3f)); /* color-1024 */
	init_pair(CUSTOM_COLORS_START + 10, CUSTOM_COLORS_START + 10, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 11, RGB_TO_NCURSES_COLOR(0xed),  RGB_TO_NCURSES_COLOR(0xc2),  RGB_TO_NCURSES_COLOR(0x2e));  /* color-2048 */
	init_pair(CUSTOM_COLORS_START + 11, CUSTOM_COLORS_START + 11, CUSTOM_COLORS_START + 13);
	init_color(CUSTOM_COLORS_START + 12, RGB_TO_NCURSES_COLOR(0x77),  RGB_TO_NCURSES_COLOR(0x6e),  RGB_TO_NCURSES_COLOR(0x65));  /* text-color */
	init_color(CUSTOM_COLORS_START + 13, RGB_TO_NCURSES_COLOR(0xf9),  RGB_TO_NCURSES_COLOR(0xf6),  RGB_TO_NCURSES_COLOR(0xf2));  /* text-color-white */
	init_color(CUSTOM_COLORS_START + 14, RGB_TO_NCURSES_COLOR(0xbb),  RGB_TO_NCURSES_COLOR(0xad),  RGB_TO_NCURSES_COLOR(0xa0));  /* board-color */
	init_pair(CUSTOM_COLORS_START + 14, CUSTOM_COLORS_START + 14, CUSTOM_COLORS_START + 14);
}

